skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stakitty = "8dFfRCbNDeYt9y96ZC8uCcU2BbXt2LwWEH91ZUN3BRQg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
